export const homeObjOne = {
    id: 'AboutMe',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Kimberly Salas',
    headline: 'Full-Stack Web Developer',
    description: 'A Full Stack Developer capable of producing scalable software solutions. Also, a team player with a knack for visual design and utility.',
    buttonLabel: "About Me",
    imgStart: true,
    img: require("../../images/aboutme.svg"),
    alt: "KS",
    dark: true,
    primary: true,
    darkText: false,
};

export const homeObjTwo = {
    id: 'Contact',
    lightBg: true,
    lightText: false,
    lightTextDesc: true,
    // topLine: 'Contact Me',
    headline: 'Contact Me',
    description: 'Feel free to contact me!',
    buttonLabel: "Github",
    imgStart: false,
    img: ('../../images/contact.svg'),
    alt: 'salask',
    dark: false,
    primary: false,
    darkText: true,
};
export const homeObjThree = {
    id: 'Projects',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    // topLine: 'Resume',
    headline: 'Projects',
    description: 'A Full Stack Developer capable of producing scalable software solutions. Also, a team player with a knack for visual design and utility.',
    // buttonLabel: "About Me",
    imgStart: false,
    img: ('/'),
    alt: 'salask',
    dark: true,
    primary: true,
    darkText: false,
};
export const homeObjFour = {
    id: 'Resume',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    // topLine: 'Resume',
    headline: 'Resume',
    description: '',
    // buttonLabel: "About Me",
    imgStart: true,
    img: ('../../images/resume.svg'),
    alt: 'salask',
    dark: true,
    primary: true,
    darkText: false,
};