export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Kimberly Salas',
    headline: 'Full-Stack Web Developer',
    description: 'A Full Stack Developer capable of producing scalable software solutions. Also, a team player with a knack for visual design and utility.',
    buttonLabel: "About Me",
    imgStart: true,
    img: require('../../images/kim-1.JPG'),
    alt: 'salask',
    dark: true,
    primary: true,
    darkText: false,
};

export const homeObjTwo = {
    id: 'Portfolio',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Kimberly Salas',
    headline: 'Full-Stack Web Developer',
    description: 'A Full Stack Developer capable of producing scalable software solutions. Also, a team player with a knack for visual design and utility.',
    buttonLabel: "About Me",
    imgStart: false,
    img: require('../../images/kim-1.JPG'),
    alt: 'salask',
    dark: false,
    primary: false,
    darkText: true,
};

export const homeObjThree = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Kimberly Salas',
    headline: 'Full-Stack Web Developer',
    description: 'A Full Stack Developer capable of producing scalable software solutions. Also, a team player with a knack for visual design and utility.',
    buttonLabel: "About Me",
    imgStart: true,
    img: require('../../images/kim-1.JPG'),
    alt: 'salask',
    dark: true,
    primary: true,
    darkText: false,
};